import { useState } from "react";
import {
  Trash2,
  CheckCheck,
  Check,
  Inbox
} from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { useDately } from "@/context/DatelyContext";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
export default function NotificationsPage() {
  const {
    notifications,
    markNotificationRead,
    markAllNotificationsRead,
    deleteNotification,
    isLoaded
  } = useDately();
  const [activeCategory, setActiveCategory] = useState("All");
  if (!isLoaded) {
    return <DashboardLayout><div className="flex items-center justify-center min-h-[60vh]"><div className="animate-spin rounded-full h-10 w-10 border-b-2 border-dately-primary" /></div></DashboardLayout>;
  }
  const filteredNotifs = (notifications || []).filter((notif) => {
    if (activeCategory === "Unread") return !notif?.read;
    if (activeCategory === "Reminders") return notif?.category === "Reminder";
    if (activeCategory === "System") return notif?.category === "System";
    return true;
  });
  const getCategoryColor = (type) => {
    switch (type) {
      case "danger":
        return "bg-dately-danger/10 text-dately-danger border-dately-danger/25";
      case "warning":
        return "bg-dately-warning/10 text-dately-warning border-dately-warning/25";
      case "success":
        return "bg-dately-success/10 text-dately-success border-dately-success/25";
      default:
        return "bg-blue-50 text-blue-600 border-blue-100";
    }
  };
  return <DashboardLayout><div className="space-y-6 text-left">{
    /* Header */
  }<div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 className="text-2xl font-extrabold text-dately-navy">Notifications Center</h1><p className="text-sm text-dately-slate mt-1">
              Review history logs and alerts generated by Dately.
            </p></div>{notifications.some((n) => !n.read) && <Button
    variant="outline"
    size="sm"
    onClick={markAllNotificationsRead}
    className="flex items-center self-start"
  ><CheckCheck className="w-4 h-4 mr-1.5" /><span>Mark all as read</span></Button>}</div>{
    /* Toolbar categories */
  }<div className="flex items-center space-x-1.5 overflow-x-auto pb-2 border-b border-dately-navy/25 scrollbar-none">{["All", "Unread", "Reminders", "System"].map((cat) => <button
    key={cat}
    onClick={() => setActiveCategory(cat)}
    className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-bold whitespace-nowrap transition-colors border-0 cursor-pointer ${activeCategory === cat ? "bg-dately-primary text-white" : "bg-dately-background text-dately-slate hover:bg-slate-100 hover:text-dately-navy"}`}
  >{cat}</button>)}</div>{
    /* List items */
  }{filteredNotifs.length === 0 ? <div className="bg-white border border-dately-border rounded-2xl p-12 text-center max-w-md mx-auto space-y-4 shadow-sm"><div className="w-12 h-12 bg-dately-primary/5 text-dately-slate rounded-full flex items-center justify-center mx-auto"><Inbox className="w-6 h-6" /></div><h3 className="font-extrabold text-dately-navy text-base">Inbox Empty</h3><p className="text-sm text-dately-slate">No notification alerts listed in this category view.</p></div> : <div className="bg-white border border-dately-border rounded-2xl shadow-sm overflow-hidden divide-y divide-dately-border">{filteredNotifs.map((notif) => <div
    key={notif.id}
    className={`p-4 sm:p-5 flex items-start justify-between gap-4 transition-all ${!notif.read ? "bg-slate-50/60" : ""}`}
  ><div className="flex items-start space-x-3.5 text-left min-w-0"><span
    className={`w-2.5 h-2.5 mt-2 rounded-full flex-shrink-0 ${!notif.read ? "bg-dately-primary" : "bg-transparent"}`}
  /><div className="min-w-0"><div className="flex items-center space-x-2"><h4 className={`text-sm sm:text-base truncate ${!notif.read ? "font-extrabold text-slate-900" : "font-semibold text-slate-800"}`}>{notif.title}</h4><Badge variant="neutral" className="text-xs px-2 py-0.5">{notif.category}</Badge></div><p className="text-xs sm:text-sm text-slate-700 font-medium mt-1 leading-relaxed">{notif.message}</p><span className="text-xs text-slate-500 mt-2 block font-sans font-semibold">
  {(() => {
    const d = new Date(notif.createdAt);
    return isNaN(d.getTime()) ? "N/A" : d.toLocaleDateString("en-IN", {
      day: "numeric",
      month: "short",
      hour: "numeric",
      minute: "2-digit"
    });
  })()}
</span></div></div><div className="flex items-center space-x-1 flex-shrink-0">{!notif.read && <button
    onClick={() => markNotificationRead(notif.id)}
    className="p-2 hover:bg-slate-100 text-dately-slate hover:text-dately-success rounded-lg transition-colors bg-transparent border-0 cursor-pointer"
    title="Mark as read"
  ><Check className="w-4.5 h-4.5" /></button>}<button
    onClick={() => deleteNotification(notif.id)}
    className="p-2 hover:bg-red-50 text-dately-slate hover:text-dately-danger rounded-lg transition-colors bg-transparent border-0 cursor-pointer"
    title="Delete Notification"
  ><Trash2 className="w-4.5 h-4.5" /></button></div></div>)}</div>}</div></DashboardLayout>;
}
